//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicPerformance
    {
        public int IDAP { get; set; }
        public Nullable<int> IDStudent { get; set; }
        public Nullable<int> IDSubject { get; set; }
        public Nullable<int> Evaluation { get; set; }
        public Nullable<int> DateEvaluation { get; set; }
    
        public virtual SchoolSubject SchoolSubject { get; set; }
        public virtual Students Students { get; set; }
    }
}
