//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolProjectWPFEntities : DbContext
    {
        public SchoolProjectWPFEntities()
            : base("name=SchoolProjectWPFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicPerformance> AcademicPerformance { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<SchoolSubject> SchoolSubject { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Weekend> Weekend { get; set; }
    }
}
