//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int IDSchedule { get; set; }
        public Nullable<int> IDTeacher { get; set; }
        public Nullable<int> IDSubject { get; set; }
        public Nullable<int> IDWeekend { get; set; }
        public Nullable<int> NumberSubject { get; set; }
    
        public virtual SchoolSubject SchoolSubject { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Weekend Weekend { get; set; }
    }
}
