//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.AcademicPerformance = new HashSet<AcademicPerformance>();
        }
    
        public int IDStudent { get; set; }
        public string NameStudent { get; set; }
        public string LoginStudent { get; set; }
        public string PasswordStudent { get; set; }
        public Nullable<System.DateTime> BithdayStudent { get; set; }
        public string EmailStudent { get; set; }
        public Nullable<int> IDGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicPerformance> AcademicPerformance { get; set; }
        public virtual Group Group { get; set; }
    }
}
